spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost/conta_db?createDataBaseIfNotExist=ture&useTimezone=true&serverTimezone=UTC
    username: postgres
    password: PsqlPass
    driver-class-name: org.postgresql.Driver
  jpa:
    
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000

